# Generated by Django 3.1.3 on 2021-03-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20210309_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='mobile_number',
            field=models.CharField(max_length=16),
        ),
    ]
